# Generated by Django 3.2.5 on 2021-07-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisee", "0001_initial"),
        ("advisor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("I", "Initiated"),
                            ("E", "Established"),
                            ("T", "Terminated"),
                            ("O", "Others"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "advisee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisee.advisee",
                    ),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisor.advisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdivsorRelationshipBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("billing_amount", models.IntegerField(blank=True, null=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisor.advisorrelationship",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advisor",
            name="clients",
            field=models.ManyToManyField(
                through="advisor.AdvisorRelationship", to="advisee.Advisee"
            ),
        ),
    ]
