# Generated by Django 3.2.5 on 2021-07-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advisor", "0002_auto_20210715_0823"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdivsorRelationshipBilling",
            new_name="AdvisorRelationshipBilling",
        ),
    ]
