# Generated by Django 3.2.5 on 2021-07-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advisees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                    ),
                ),
                (
                    "assessment_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "advisee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisees.advisee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessmentquestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filled_date", models.DateTimeField(auto_now=True)),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("S", "Up to 12th"),
                            ("B", "Bachelor’s Degree"),
                            ("M", "Master’s Degree"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "advisee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisees.advisee",
                    ),
                ),
            ],
        ),
    ]
