# Generated by Django 3.2.5 on 2021-07-15 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adivsorrelationshipbilling",
            name="billing_period",
        ),
        migrations.AddField(
            model_name="adivsorrelationshipbilling",
            name="billing_period_end",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adivsorrelationshipbilling",
            name="billing_period_start",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
