# Generated by Django 3.2.5 on 2021-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                ("numeric_code", models.CharField(max_length=3)),
                (
                    "name",
                    models.CharField(
                        help_text="Human Readable name for currency.", max_length=100
                    ),
                ),
            ],
        ),
    ]
