# Generated by Django 3.2.5 on 2021-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile_photos/"
            ),
        ),
    ]
