# Generated by Django 3.2.5 on 2021-07-16 11:00
from django.db import migrations
from pycountry import currencies


def load_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    currencies_to_create = []
    for curr in currencies:
        currencies_to_create.append(
            Currency(
                code=curr.alpha_3,
                name=curr.name,
                numeric_code=curr.numeric,
            )
        )
    Currency.objects.bulk_create(currencies_to_create)


def delete_all_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_currency"),
    ]

    operations = [
        migrations.RunPython(load_currencies, reverse_code=delete_all_currencies),
    ]
