# Generated by Django 3.2.5 on 2021-07-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_load_currencies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ("code",), "verbose_name_plural": "Currencies"},
        ),
    ]
