# Generated by Django 3.2.5 on 2021-07-16 09:33

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advisees", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisor",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("core.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdvisorRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("I", "Initiated"),
                            ("E", "Established"),
                            ("T", "Terminated"),
                            ("O", "Others"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "advisee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisees.advisee",
                    ),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisors.advisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvisorRelationshipBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("billing_amount", models.IntegerField(blank=True, null=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisors.advisorrelationship",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advisor",
            name="clients",
            field=models.ManyToManyField(
                through="advisors.AdvisorRelationship", to="advisees.Advisee"
            ),
        ),
    ]
