# Generated by Django 3.2.5 on 2021-07-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advisees", "0004_auto_20210716_1137"),
        ("core", "0005_alter_customuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of this income, used to help identify it quickly. For example, Salary.",
                        max_length=200,
                    ),
                ),
                (
                    "annual_value",
                    models.PositiveBigIntegerField(
                        help_text="Post tax amount earned, per annum."
                    ),
                ),
                (
                    "income_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Salary"),
                            (1, "Rental"),
                            (2, "Business"),
                            (3, "Pension"),
                            (4, "Interest"),
                            (5, "ROYALTY"),
                            (6, "Commission"),
                            (7, "Other"),
                        ]
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.currency"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advisees.advisee",
                    ),
                ),
            ],
            options={
                "ordering": ("owner", "source", "-annual_value"),
            },
        ),
    ]
