# Generated by Django 3.2.5 on 2021-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flows", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={"ordering": ("owner", "income_type", "-annual_value")},
        ),
        migrations.RemoveField(
            model_name="income",
            name="source",
        ),
        migrations.AddField(
            model_name="income",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Any additional information or comments."
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="income_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Salary"),
                    (1, "Rental"),
                    (2, "Business"),
                    (3, "Pension"),
                    (4, "Interest"),
                    (5, "Royalty"),
                    (6, "Commission"),
                    (7, "Other"),
                ]
            ),
        ),
    ]
