# Generated by Django 3.2.5 on 2021-07-16 12:18

from django.db import migrations

INCOME_TYPES = {
    "Earned Income": [
        "Salary",
        "Commission",
    ],
    "Passive Income": [
        "Rental",
        "Pension",
        "Royalty",
        "Business",
    ],
    "Portfolio Income": [
        "Interest",
        "Trading",
    ],
    "Other": [
        "Other",
    ],
}

EXPENSE_TYPES = {
    "Basic": [
        "Food & Groceries",
        "Rent",
        "House Maintenance",
        "Shopping",
        "Domestic Help",
        "Medical",
        "Clothing",
        "Miscellenous",
    ],
    "Bills/ Utilities": [
        "Mobile",
        "Water",
        "Electricity",
        "Internet",
        "Telephone",
        "DTH",
        "Gas",
        "Online Subscriptions",
        "Others",
    ],
    "Child Care": [
        "Education - Fees",
        "Kid's Activities",
        "Others",
    ],
    "Elderly Care": [
        "Nurse/ Domestic Help",
        "Activities",
        "Medicine",
        "Others",
    ],
    "Entertainment": [
        "Restaurant",
        "Others",
        "Vacation",
        "Movies",
    ],
    "Miscellaneous": [
        "Donations",
        "Doctor Fees",
        "Personal Care",
        "Professional Fees",
        "Others",
    ],
}


def load_cash_flow_types(apps, schema_editor):
    IncomeCategory = apps.get_model("cash_flows", "IncomeCategory")
    IncomeType = apps.get_model("cash_flows", "IncomeType")
    ExpenseCategory = apps.get_model("cash_flows", "ExpenseCategory")
    ExpenseType = apps.get_model("cash_flows", "ExpenseType")

    for category_name, income_types in INCOME_TYPES.items():
        category = IncomeCategory.objects.create(name=category_name)
        for income_type in income_types:
            IncomeType.objects.create(
                category=category,
                name=income_type,
            )

    for category_name, expense_types in EXPENSE_TYPES.items():
        category = ExpenseCategory.objects.create(name=category_name)
        for expense_type in expense_types:
            ExpenseType.objects.create(
                category=category,
                name=expense_type,
            )


def delete_all_cash_flow_types(apps, schema_editor):
    IncomeCategory = apps.get_model("cash_flows", "IncomeCategory")
    IncomeType = apps.get_model("cash_flows", "IncomeType")
    ExpenseCategory = apps.get_model("cash_flows", "ExpenseCategory")
    ExpenseType = apps.get_model("cash_flows", "ExpenseType")

    for model in [IncomeType, ExpenseType, IncomeCategory, ExpenseCategory]:
        model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flows", "0004_auto_20210716_1218"),
    ]

    operations = [
        migrations.RunPython(
            load_cash_flow_types, reverse_code=delete_all_cash_flow_types
        ),
    ]
