# Generated by Django 3.2.5 on 2021-07-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advisees", "0004_auto_20210716_1137"),
        ("core", "0005_alter_customuser_options"),
        ("cash_flows", "0005_load_cash_flow_types"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Expenses",
            new_name="Expense",
        ),
    ]
