# Generated by Django 3.2.5 on 2021-07-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flows", "0006_rename_expenses_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incometype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="income_types",
                to="cash_flows.incomecategory",
            ),
        ),
    ]
