# Generated by Django 3.2.5 on 2021-07-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flows", "0007_alter_incometype_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensetype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_types",
                to="cash_flows.expensecategory",
            ),
        ),
    ]
